#!/usr/bin/env node
/**
 * Generate the typed OpenAPI client from FastAPI's /openapi.json.
 *
 * Usage:
 *   pnpm --filter @petrobrain/api gen -- --url http://localhost:8000/openapi.json
 *   pnpm --filter @petrobrain/api gen -- --file ../PetroBrain/openapi.json
 *
 * Output: src/generated/openapi.ts (consumed by openapi-fetch via the
 * paths type, so route paths, method names, and payloads are all checked
 * at compile time).
 */
import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import openapiTS, { astToString } from 'openapi-typescript';

const here = dirname(fileURLToPath(import.meta.url));
const outFile = resolve(here, '..', 'src', 'generated', 'openapi.ts');

const args = parseArgs(process.argv.slice(2));
if (!args.url && !args.file) {
  console.error(
    'usage: pnpm --filter @petrobrain/api gen -- --url <openapi-url> | --file <openapi-json-path>',
  );
  process.exit(2);
}

const source = args.url ? new URL(args.url) : resolve(process.cwd(), args.file);

try {
  const ast = await openapiTS(source);
  const banner =
    '// AUTO-GENERATED by scripts/gen.mjs. Do not edit by hand.\n' +
    `// Source: ${args.url ?? args.file}\n` +
    `// Generated: ${new Date().toISOString()}\n\n`;
  await mkdir(dirname(outFile), { recursive: true });
  await writeFile(outFile, banner + astToString(ast), 'utf8');
  console.log(`wrote ${outFile}`);
} catch (err) {
  console.error('openapi-typescript failed:', err);
  process.exit(1);
}

function parseArgs(argv) {
  const out = {};
  for (let i = 0; i < argv.length; i += 1) {
    const k = argv[i];
    const v = argv[i + 1];
    if (k === '--url') {
      out.url = v;
      i += 1;
    } else if (k === '--file') {
      out.file = v;
      i += 1;
    }
  }
  return out;
}
